### ISSUE TITLE
couldn't find "libtailor.so"

### ISSUE THREAD

**Issue by JasonLinkinBright** [bytedance/tailor#3]
运行demo，找不到so
`2020-12-17 17:39:18.252 27105-27105/com.bytedance.demo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.bytedance.demo, PID: 27105
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.bytedance.demo-CKMQ9X0L46A-DkP2K_dqqg==/base.apk"],nativeLibraryDirectories=[/data/app/com.bytedance.demo-CKMQ9X0L46A-DkP2K_dqqg==/lib/arm, /data/app/com.bytedance.demo-CKMQ9X0L46A-DkP2K_dqqg==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]] couldn't find "libtailor.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1669)
        at com.bytedance.tailor.Tailor.<clinit>(Tailor.java:28)
        at com.bytedance.tailor.Tailor.isHprofValid(Tailor.java:46)
        at com.bytedance.demo.MainActivity.tailor_for_file(MainActivity.java:42)
        at com.bytedance.demo.MainActivity.onClick(MainActivity.java:33)
        at android.view.View.performClick(View.java:7352)
        at android.widget.TextView.performClick(TextView.java:14230)
        at android.view.View.performClickInternal(View.java:7318)
        at android.view.View.access$3200(View.java:846)
        at android.view.View$PerformClick.run(View.java:27800)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7050)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
`

**Comment by shentianzhou** [comment]
是什么机型？

**Comment by JasonLinkinBright** [comment]
> 是什么机型？

三星S8，
Android 9.0 版本

**Comment by dingqiqi** [comment]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.bytedance.demo-F9s00JEAw90nypV06DrKIg==/base.apk"],nativeLibraryDirectories=[/data/app/com.bytedance.demo-F9s00JEAw90nypV06DrKIg==/lib/arm, /data/app/com.bytedance.demo-F9s00JEAw90nypV06DrKIg==/base.apk!/lib/armeabi-v7a, /system/lib, /product/lib]]] couldn't find "libtailor.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1672)
        at com.bytedance.tailor.Tailor.<clinit>(Tailor.java:28)
        at com.bytedance.tailor.Tailor.isHprofValid(Tailor.java:46)
        at com.bytedance.demo.MainActivity.tailor_for_file(MainActivity.java:42)
        at com.bytedance.demo.MainActivity.onClick(MainActivity.java:33)
        at android.view.View.performClick(View.java:6663)
        at android.view.View.performClickInternal(View.java:6635)
        at android.view.View.access$3100(View.java:794)
        at android.view.View$PerformClick.run(View.java:26199)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

华为M5     android：9.0

**Comment by shentianzhou** [comment]
这个一种可能是你本地的ndk配置有问题，你试试把demo/build.gradle里的api project(":library")改成implementation 'com.bytedance.tailor:library:1.0.2'
